#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Ender_AIO_Changes.h
 * Alert about Ender_AIO_Configuration.h changes at compile-time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define ENDER_AIO_VERSION 20241019

#ifdef ENDER_AIO_E_STEPS_PER_UNIT_CUSTOM
  #error "ENDER_AIO_E_STEPS_PER_UNIT_CUSTOM is now ENDER_AIO_CUSTOM_E_STEPS. Please update your configuration."
#elif defined(ENDER_AIO_CUSTOM_BLTOUCH_MOUNT)
  #error "ENDER_AIO_CUSTOM_BLTOUCH_MOUNT is now ENDER_AIO_BLTOUCH_MOUNT_CUSTOM. Please update your configuration."
#elif defined(ENDER_AIO_CUSTOM_MICROPROBE_MOUNT)
  #error "ENDER_AIO_CUSTOM_MICROPROBE_MOUNT is now ENDER_AIO_MICROPROBE_MOUNT_CUSTOM. Please update your configuration."
#endif
