#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Ender_AIO_SanityCheck.h
 * Validate Ender_AIO_Configuration.h options at compile-time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define ENDER_AIO_VERSION 20241019

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

#if MANY(ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V1_2, ENDER_AIO_MOTHERBOARD_BTT_SKR_E3_TURBO, ENDER_AIO_MOTHERBOARD_BTT_SKR_V3_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ)
  #error "Only one ENDER_AIO_MOTHERBOARD option can be enabled at a time."
#elif NONE(ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V1_2, ENDER_AIO_MOTHERBOARD_BTT_SKR_E3_TURBO, ENDER_AIO_MOTHERBOARD_BTT_SKR_V3_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ)
  #error "Invalid ENDER_AIO_MOTHERBOARD option."
#endif

//===========================================================================
//============================== Input Shaping ==============================
//===========================================================================

#if ENABLED(ENDER_AIO_INPUT_SHAPING)
  #ifndef ENDER_AIO_SHAPING_FREQ_X
    #error "ENDER_AIO_SHAPING_FREQ_X is invalid or not defined."
  #elif !defined(ENDER_AIO_SHAPING_FREQ_Y)
    #error "ENDER_AIO_SHAPING_FREQ_Y is invalid or not defined."
  #elif !defined(ENDER_AIO_SHAPING_ZETA_X)
    #error "ENDER_AIO_SHAPING_ZETA_X is invalid or not defined."
  #elif !defined(ENDER_AIO_SHAPING_ZETA_Y)
    #error "ENDER_AIO_SHAPING_ZETA_Y is invalid or not defined."
  #endif
#endif

//===========================================================================
//================================ Extruder =================================
//===========================================================================

#if MANY(ENDER_AIO_EXTRUDER_STOCK, ENDER_AIO_EXTRUDER_WINSINN_DUAL_GEAR, ENDER_AIO_EXTRUDER_BONDTECH_BMG, ENDER_AIO_EXTRUDER_TL_DDB_V2S)
  #error "Only one ENDER_AIO_EXTRUDER option can be enabled at a time."
#elif NONE(ENDER_AIO_EXTRUDER_STOCK, ENDER_AIO_EXTRUDER_WINSINN_DUAL_GEAR, ENDER_AIO_EXTRUDER_BONDTECH_BMG, ENDER_AIO_EXTRUDER_TL_DDB_V2)
  #error "Invalid ENDER_AIO_EXTRUDER option."
#endif

#if NONE(ENDER_AIO_EXTRUDER_BONDTECH_BMG, ENDER_AIO_EXTRUDER_TL_DDB_V2) && ENABLED(ENDER_AIO_EXTRUDER_MOTOR_LDO_0_9_SLIM_POWER)
  #error "ENDER_AIO_EXTRUDER_MOTOR_LDO_0_9_SLIM_POWER is not supported on enabled extruder."
#endif

//===========================================================================
//========================= Thermal & PID Settings ==========================
//===========================================================================

#if ENABLED(ENDER_AIO_CUSTOM_HOTEND_PID)
  #ifndef ENDER_AIO_DEFAULT_Kp
    #error "ENDER_AIO_DEFAULT_Kp is invalid or not defined."
  #elif !defined(ENDER_AIO_DEFAULT_Ki)
    #error "ENDER_AIO_DEFAULT_Ki is invalid or not defined."
  #elif !defined(ENDER_AIO_DEFAULT_Kd)
    #error "ENDER_AIO_DEFAULT_Kd is invalid or not defined."
  #endif
#endif

#if ENABLED(ENDER_AIO_CUSTOM_BED_PID)
  #ifndef ENDER_AIO_DEFAULT_bedKp
    #error "ENDER_AIO_DEFAULT_bedKp is invalid or not defined."
  #elif !defined(ENDER_AIO_DEFAULT_bedKi)
    #error "ENDER_AIO_DEFAULT_bedKi is invalid or not defined."
  #elif !defined(ENDER_AIO_DEFAULT_bedKd)
    #error "ENDER_AIO_DEFAULT_bedKd is invalid or not defined."
  #endif
#endif

#if ALL(ENDER_AIO_HOTEND_MPCTEMP, ENDER_AIO_CUSTOM_HOTEND_PID)
  #error "ENDER_AIO_HOTEND_MPCTEMP and ENDER_AIO_CUSTOM_HOTEND_PID cannot be enabled at the same time."
#endif

#if ENABLED(ENDER_AIO_CUSTOM_HOTEND_MPCTEMP)
  #if DISABLED(ENDER_AIO_HOTEND_MPCTEMP)
    #error "ENDER_AIO_CUSTOM_HOTEND_MPCTEMP requires ENDER_AIO_HOTEND_MPCTEMP."
  #elif !defined(ENDER_AIO_CUSTOM_MPC_HEATER_POWER)
    #error "ENDER_AIO_CUSTOM_MPC_HEATER_POWER is invalid or not defined."
  #elif !defined(ENDER_AIO_CUSTOM_MPC_BLOCK_HEAT_CAPACITY)
    #error "ENDER_AIO_CUSTOM_MPC_BLOCK_HEAT_CAPACITY is invalid or not defined."
  #elif !defined(ENDER_AIO_CUSTOM_MPC_SENSOR_RESPONSIVENESS)
    #error "ENDER_AIO_CUSTOM_MPC_SENSOR_RESPONSIVENESS is invalid or not defined."
  #elif !defined(ENDER_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF)
    #error "ENDER_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF is invalid or not defined."
  #elif !defined(ENDER_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255)
    #error "ENDER_AIO_CUSTOM_MPC_AMBIENT_XFER_COEFF_FAN255 is invalid or not defined."
  #elif !defined(ENDER_AIO_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM)
    #error "ENDER_AIO_CUSTOM_FILAMENT_HEAT_CAPACITY_PERMM is invalid or not defined."
  #endif
#endif

//===========================================================================
//========================== Probes / Bed Leveling ==========================
//===========================================================================

#if MANY(ENDER_AIO_BLTOUCH, ENDER_AIO_MICROPROBE)
  #error "Only one probe option can be enabled at a time."
#endif

#if ENABLED(ENDER_AIO_HAS_PROBE)
  #if MANY(ENDER_AIO_AUTO_BED_LEVELING_BILINEAR, ENDER_AIO_AUTO_BED_LEVELING_UBL)
    #error "Only one ENDER_AIO_AUTO_BED_LEVELING option can be enabled at a time."
  #elif NONE(ENDER_AIO_AUTO_BED_LEVELING_BILINEAR, ENDER_AIO_AUTO_BED_LEVELING_UBL)
    #error "Invalid ENDER_AIO_AUTO_BED_LEVELING option."
  #endif
#elif ENABLED(ENDER_AIO_BLTOUCH)
  #if MANY(ENDER_AIO_BLTOUCH_MOUNT_CREALITY_METAL, ENDER_AIO_BLTOUCH_MOUNT_DUDE_IN_A_BOX) || (ANY(ENDER_AIO_BLTOUCH_MOUNT_CREALITY_METAL, ENDER_AIO_BLTOUCH_MOUNT_DUDE_IN_A_BOX) && defined(ENDER_AIO_BLTOUCH_MOUNT_CUSTOM))
    #error "Only one ENDER_AIO_BLTOUCH_MOUNT option can be enabled at a time."
  #elif NONE(ENDER_AIO_BLTOUCH_MOUNT_CREALITY_METAL, ENDER_AIO_BLTOUCH_MOUNT_DUDE_IN_A_BOX) && !defined(ENDER_AIO_BLTOUCH_MOUNT_CUSTOM)
    #error "Invalid ENDER_AIO_BLTOUCH_MOUNT option."
  #endif
#elif ENABLED(ENDER_AIO_MICROPROBE)
  #if ENABLED(ENDER_AIO_MICROPROBE_MOUNT_METAL) && defined(ENDER_AIO_MICROPROBE_MOUNT_CUSTOM)
    #error "Only one ENDER_AIO_MICROPROBE_MOUNT option can be enabled at a time."
  #elif DISABLED(ENDER_AIO_MICROPROBE_MOUNT_METAL) && !defined(ENDER_AIO_MICROPROBE_MOUNT_CUSTOM)
    #error "Invalid ENDER_AIO_MICROPROBE_MOUNT option."
  #endif

  // Ensure homing works correctly since MicroProbe V2 needs a strong pull-up.
  #if (ANY(ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1) && NONE(ENDER_AIO_MICROPROBE_V1, ENDER_AIO_PROBE_CONNECTED_TO_Z_MIN_PORT))
    #error "ENDER_AIO_PROBE_CONNECTED_TO_Z_MIN_PORT is required for enabled motherboard & MicroProbe V2. Connect probe's trigger wires to Z MIN/Z STOP instead of dedicated PROBE port."
  #endif

#endif

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if MANY(ENDER_AIO_DISPLAY_STOCK, ENDER_AIO_DISPLAY_BTT_TFT35_E3_TFT)
  #error "Only one ENDER_AIO_DISPLAY option can be enabled at a time."
#elif NONE(ENDER_AIO_DISPLAY_STOCK, ENDER_AIO_DISPLAY_BTT_TFT35_E3_TFT)
  #error "Invalid ENDER_AIO_DISPLAY option."
#endif

#ifndef ENDER_AIO_LCD_LANGUAGE
  #error "Invalid ENDER_AIO_LCD_LANGUAGE option."
#endif

//===========================================================================
//=========================== Sheet Profiles Menu ===========================
//===========================================================================

#if ENABLED(ENDER_AIO_SHEET_PROFILES_MENU) && DISABLED(ENDER_AIO_HAS_PROBE)
  #error "ENDER_AIO_SHEET_PROFILES_MENU requires a probe."
#else
  // Description is enabled, but no offset
  #if defined(ENDER_AIO_SHEET_1_DESC) && !defined(ENDER_AIO_SHEET_1_OFFSET)
    #error "ENDER_AIO_SHEET_1_OFFSET is required when ENDER_AIO_SHEET_1_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_2_DESC) && !defined(ENDER_AIO_SHEET_2_OFFSET)
    #error "ENDER_AIO_SHEET_2_OFFSET is required when ENDER_AIO_SHEET_2_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_3_DESC) && !defined(ENDER_AIO_SHEET_3_OFFSET)
    #error "ENDER_AIO_SHEET_3_OFFSET is required when ENDER_AIO_SHEET_3_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_4_DESC) && !defined(ENDER_AIO_SHEET_4_OFFSET)
    #error "ENDER_AIO_SHEET_4_OFFSET is required when ENDER_AIO_SHEET_4_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_5_DESC) && !defined(ENDER_AIO_SHEET_5_OFFSET)
    #error "ENDER_AIO_SHEET_5_OFFSET is required when ENDER_AIO_SHEET_5_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_6_DESC) && !defined(ENDER_AIO_SHEET_6_OFFSET)
    #error "ENDER_AIO_SHEET_6_OFFSET is required when ENDER_AIO_SHEET_6_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_7_DESC) && !defined(ENDER_AIO_SHEET_7_OFFSET)
    #error "ENDER_AIO_SHEET_7_OFFSET is required when ENDER_AIO_SHEET_7_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_8_DESC) && !defined(ENDER_AIO_SHEET_8_OFFSET)
    #error "ENDER_AIO_SHEET_8_OFFSET is required when ENDER_AIO_SHEET_8_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_9_DESC) && !defined(ENDER_AIO_SHEET_9_OFFSET)
    #error "ENDER_AIO_SHEET_9_OFFSET is required when ENDER_AIO_SHEET_9_DESC is enabled."
  #elif defined(ENDER_AIO_SHEET_10_DESC) && !defined(ENDER_AIO_SHEET_10_OFFSET)
    #error "ENDER_AIO_SHEET_10_OFFSET is required when ENDER_AIO_SHEET_10_DESC is enabled."
  #endif

  // Offset is enabled, but no description
  #if defined(ENDER_AIO_SHEET_1_OFFSET) && !defined(ENDER_AIO_SHEET_1_DESC)
    #error "ENDER_AIO_SHEET_1_DESC is required when ENDER_AIO_SHEET_1_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_2_OFFSET) && !defined(ENDER_AIO_SHEET_2_DESC)
    #error "ENDER_AIO_SHEET_2_DESC is required when ENDER_AIO_SHEET_2_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_3_OFFSET) && !defined(ENDER_AIO_SHEET_3_DESC)
    #error "ENDER_AIO_SHEET_3_DESC is required when ENDER_AIO_SHEET_3_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_4_OFFSET) && !defined(ENDER_AIO_SHEET_4_DESC)
    #error "ENDER_AIO_SHEET_4_DESC is required when ENDER_AIO_SHEET_4_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_5_OFFSET) && !defined(ENDER_AIO_SHEET_5_DESC)
    #error "ENDER_AIO_SHEET_5_DESC is required when ENDER_AIO_SHEET_5_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_6_OFFSET) && !defined(ENDER_AIO_SHEET_6_DESC)
    #error "ENDER_AIO_SHEET_6_DESC is required when ENDER_AIO_SHEET_6_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_7_OFFSET) && !defined(ENDER_AIO_SHEET_7_DESC)
    #error "ENDER_AIO_SHEET_7_DESC is required when ENDER_AIO_SHEET_7_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_8_OFFSET) && !defined(ENDER_AIO_SHEET_8_DESC)
    #error "ENDER_AIO_SHEET_8_DESC is required when ENDER_AIO_SHEET_8_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_9_OFFSET) && !defined(ENDER_AIO_SHEET_9_DESC)
    #error "ENDER_AIO_SHEET_9_DESC is required when ENDER_AIO_SHEET_9_OFFSET is enabled."
  #elif defined(ENDER_AIO_SHEET_10_OFFSET) && !defined(ENDER_AIO_SHEET_10_DESC)
    #error "ENDER_AIO_SHEET_10_DESC is required when ENDER_AIO_SHEET_10_OFFSET is enabled."
  #endif
#endif
