//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Ender_AIO_Warnings.cpp
 * Test Ender AIO configuration values and give warnings at compile-time.
 */
#include "MarlinConfig.h"
#define ENDER_AIO_VERSION 20241019

//
// Warnings! Located here so they will appear just once in the build output.
//

/**
 * Ender AIO Warnings / Reminders
 */
#ifndef NO_ENDER_AIO_WARNINGS

//===========================================================================
//============================= Filament Runout =============================
//===========================================================================

#if ENABLED(ENDER_AIO_BTT_SMART_FILAMENT_SENSOR_V2)

  /**
   * BTT SFS V2.0 Wiring Colors
   *
   * Switch Sensor Cable: Red wire -> VCC, Blue wire -> SENSOR
   * Motion Sensor Cable: Black wire -> GND, Green wire -> SENSOR
   */
  #if ANY(ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V2_0)
    #warning "Connect BTT SFS V2.0 Switch Sensor cable to E0-STOP: Red wire -> +5V, Blue wire -> PC15."
    #warning "Connect BTT SFS V2.0 Motion Sensor cable to PS-ON: Black wire -> GND, Green wire -> PC13."
  #elif ENABLED(ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V1_2)
    #warning "Connect BTT SFS V2.0 Switch Sensor cable to E0-STOP: Red wire -> +5V, Blue wire -> PC15."
    #warning "Connect BTT SFS V2.0 Motion Sensor cable to PT-DET: Black wire -> GND, Green wire -> PC12."
  #elif ENABLED(ENDER_AIO_MOTHERBOARD_BTT_SKR_MINI_E3_V3_0_1)
    #warning "Connect BTT SFS V2.0 Switch Sensor cable to E0-STOP: Red wire -> +5V, Blue wire -> PC15."
    #warning "Connect BTT SFS V2.0 Motion Sensor cable to PS-ON: Black wire -> GND, Green wire -> PC14."
  #elif ENABLED(ENDER_AIO_MOTHERBOARD_BTT_SKR_E3_TURBO)
    #warning "Connect BTT SFS V2.0 Switch Sensor cable to E0-STOP: Red wire -> +5V, Blue wire -> P1_26."
    #warning "Connect BTT SFS V2.0 Motion Sensor cable to E1-STOP: Black wire -> GND, Green wire -> P1_25."
  #elif ANY(ENDER_AIO_MOTHERBOARD_BTT_SKR_V3_0, ENDER_AIO_MOTHERBOARD_BTT_SKR_V3_0_EZ)
    #warning "Connect BTT SFS V2.0 Switch Sensor cable to E0DET: Red wire -> +5V, Blue wire -> PC2."
    #warning "Connect BTT SFS V2.0 Motion Sensor cable to E1DET: Black wire -> GND, Green wire -> PA0."
  #endif
#endif

#if ENABLED(ENDER_AIO_HAS_PROBE)
  #warning: "Z endstop must be removed and the probe will be used for Z homing."
#endif

#if ALL(ENDER_AIO_HAS_FIVE_DRIVERS, ENDER_AIO_DUAL_Z_KIT)
  #warning "Five stepper drivers are required for enabled motherboard. E1 stepper driver will be used for Z2."
#endif

//===========================================================================
//========================== TMC DIAG Jumpers/Pins ==========================
//===========================================================================

#if ENABLED(ENDER_AIO_SENSORLESS_HOMING)
  #if ALL(ENDER_AIO_HAS_FIVE_DRIVERS, ENDER_AIO_DUAL_Z_KIT)
    #if ENABLED(USES_DIAG_JUMPERS)
      #warning "DIAG jumpers must be installed for X & Y and removed for Z, Z2 (E1), and E0 or homing and filament runout will not work correctly."
    #elif ENABLED(USES_DIAG_PINS)
      #warning "DIAG pins must be cut or desoldered from Z, Z2 (E1), and E0 drivers or homing and filament runout will not work correctly."
    #endif
  #else // Four drivers
    #if ENABLED(USES_DIAG_JUMPERS)
      #warning "DIAG jumpers must be installed for X & Y and removed for Z & E or homing and filament runout will not work correctly."
    #elif ENABLED(USES_DIAG_PINS)
      #warning "DIAG pins must be cut or desoldered from Z and E drivers or homing and filament runout will not work correctly."
    #endif
  #endif
#else // Endstops
  #if ALL(ENDER_AIO_HAS_FIVE_DRIVERS, ENDER_AIO_DUAL_Z_KIT)
    #if ENABLED(USES_DIAG_JUMPERS)
      #warning "DIAG jumpers must be removed for X, Y, Z, Z2 (E1), & E0 or homing and filament runout will not work correctly."
    #elif ENABLED(USES_DIAG_PINS)
      #warning "DIAG pins must be cut or desoldered from X, Y, Z, Z2 (E1), and E0 drivers or homing and filament runout will not work correctly."
    #endif
  #else // Four drivers
    #if ENABLED(USES_DIAG_JUMPERS)
      #warning "DIAG jumpers must be removed for X, Y, Z, & E0 or homing and filament runout will not work correctly."
    #elif ENABLED(USES_DIAG_PINS)
      #warning "DIAG pins must be cut or desoldered from X, Y, Z, and E0 drivers or homing and filament runout will not work correctly."
    #endif
  #endif
#endif

#endif // NO_ENDER_AIO_WARNINGS

//===========================================================================
//============================== Please Donate ==============================
//===========================================================================

#warning "If you find this project helpful, please consider donating at https://github.com/sponsors/thisiskeithb or https://ko-fi.com/thisiskeithb"
