#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

/**
 * Ender_AIO_Conditionals_SanityCheck.h
 * Validate final Ender_AIO_Conditionals.h options at compile-time.
 */
#define CONFIGURATION_H_VERSION 02010300
#define ENDER_AIO_VERSION 20230701

//===========================================================================
//========================= LCD / TFT / Controller ==========================
//===========================================================================

#if ALL(ENDER_AIO_SINGLE_EXP_CONNECTION, ENDER_AIO_USES_BOTH_EXP_CABLES)
  #error "ENDER_AIO_USES_BOTH_EXP_CABLES is incompatible with enabled motherboard."
#endif
